"use client";

import { KeyRound, Trash2 } from "lucide-react";
import { useEffect, useState, useTransition } from "react";
import { dashboardFetch } from "@/lib/dashboard-api";

type ApiKey = {
  id: string;
  name: string;
  token?: string;
  prefix: string;
  mode: "live" | "test";
  scopes: string[];
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
};

export function DashboardApiKeys() {
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [error, setError] = useState("");
  const [isPending, startTransition] = useTransition();

  async function loadKeys() {
    const result = await dashboardFetch("/v1/account/api-keys?limit=100");
    setKeys(result.data ?? []);
  }

  useEffect(() => {
    loadKeys().catch((err) => setError(err.message));
  }, []);

  async function createKey(formData: FormData) {
    setError("");
    const name = String(formData.get("name") ?? "").trim();
    const mode = String(formData.get("mode") ?? "test");
    const scopes = String(formData.get("scopes") ?? "trackings:read,trackings:write").split(",").map((scope) => scope.trim());
    startTransition(async () => {
      try {
        const key = await dashboardFetch("/v1/account/api-keys", {
          method: "POST",
          body: JSON.stringify({ name: name || "Dashboard key", mode, scopes }),
        });
        setKeys((current) => [key, ...current]);
      } catch (err) {
        setError((err as Error).message);
      }
    });
  }

  async function revokeKey(id: string) {
    setError("");
    startTransition(async () => {
      try {
        await dashboardFetch(`/v1/account/api-keys/${id}`, { method: "DELETE" });
        await loadKeys();
      } catch (err) {
        setError((err as Error).message);
      }
    });
  }

  return (
    <>
      <form action={createKey} className="panel pad span-4">
        <h2>Create key</h2>
        <p>Keys are generated by the API and shown once. Store the token before leaving this page.</p>
        <label className="field">Name<input name="name" placeholder="Production checkout" /></label>
        <label className="field">Mode<select name="mode"><option>test</option><option>live</option></select></label>
        <label className="field">Scopes<input name="scopes" defaultValue="trackings:read,trackings:write" /></label>
        <button className="button primary" disabled={isPending} type="submit"><KeyRound size={16} /> {isPending ? "Creating..." : "Create"}</button>
        {error ? <p className="form-error">{error}</p> : null}
      </form>
      <div className="panel span-8 table-wrap">
        {keys.length ? (
          <table className="table">
            <thead><tr><th>Name</th><th>Token</th><th>Scopes</th><th>Status</th><th>Action</th></tr></thead>
            <tbody>
              {keys.map((key) => (
                <tr key={key.id}>
                  <td><strong>{key.name}</strong><br />{key.id}<br />{new Date(key.created_at).toLocaleString()}</td>
                  <td><code>{key.token ?? `${key.prefix}_...`}</code>{key.token ? <p className="form-note">Shown once.</p> : null}</td>
                  <td>{key.scopes.join(", ")}</td>
                  <td>{key.revoked_at ? "Revoked" : key.last_used_at ? `Used ${new Date(key.last_used_at).toLocaleString()}` : "Active"}</td>
                  <td><button className="button" disabled={Boolean(key.revoked_at) || isPending} onClick={() => revokeKey(key.id)}><Trash2 size={15} /> Revoke</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="empty-state">
            <p className="eyebrow">No keys created in this session</p>
            <h2>Create a key before registering trackings.</h2>
            <p>Persisted keys will appear here with prefix, scopes, last used time, and revoke controls.</p>
          </div>
        )}
      </div>
    </>
  );
}
