export type MarketingPage = {
  slug: string;
  eyebrow: string;
  title: string;
  summary: string;
  bullets: string[];
  proof: string;
};

export const productPages: MarketingPage[] = [
  {
    slug: "tracking-api",
    eyebrow: "Product",
    title: "Tracking API",
    summary: "A normalized REST API for registering, monitoring, bulk querying, and refreshing shipments across a global carrier network.",
    bullets: ["Create and dedupe trackings", "Bulk register and lookup", "Cached reads with live retrack controls", "Snake-case JSON and ISO timestamps"],
    proof: "Built around the same shipment event model that powers dashboards, webhooks, and customer-facing pages.",
  },
  {
    slug: "webhooks",
    eyebrow: "Product",
    title: "Webhook delivery",
    summary: "Signed shipment events with retries, replay protection, test fires, and an inbox for debugging failed customer endpoints.",
    bullets: ["HMAC SHA-256 signatures", "Exponential retry windows", "Dead-letter delivery records", "Status-change event taxonomy"],
    proof: "Designed for webhook-first operations instead of manual customer-side status checks.",
  },
  {
    slug: "white-label-tracking",
    eyebrow: "Product",
    title: "White-label tracking pages",
    summary: "Customer-facing package pages on your domain with brand controls, shipment timelines, support links, and clean public links.",
    bullets: ["Custom logo and theme", "Embeddable widget path", "Public share URLs", "No carrier-page leakage"],
    proof: "Keeps buyers inside the merchant experience with clean timelines and brand-safe delivery updates.",
  },
  {
    slug: "dashboard",
    eyebrow: "Product",
    title: "Operations dashboard",
    summary: "Shipment lists, carrier health, webhook inboxes, API keys, usage, billing, and white-label setup in one console.",
    bullets: ["Trackings table and filters", "API key management", "Webhook retry inspector", "Usage and quota surfaces"],
    proof: "Modeled after the reports teams actually need: status mix, carrier performance, and failed pushes.",
  },
  {
    slug: "carrier-detection",
    eyebrow: "Product",
    title: "Carrier detection",
    summary: "Tracking-number pattern detection, carrier candidate ranking, and registry-driven metadata for global coverage.",
    bullets: ["Prefix and format rules", "Check-digit hooks", "Ordered carrier candidates", "Community adapter registry"],
    proof: "A migration-friendly replacement for manually selecting carriers in every workflow.",
  },
  {
    slug: "analytics",
    eyebrow: "Product",
    title: "Shipment analytics",
    summary: "Performance views for delivery speed, carrier reliability, exception trends, webhook health, and tracking-page engagement.",
    bullets: ["Carrier SLA views", "Exception clustering", "Transit-time benchmarks", "Webhook success reporting"],
    proof: "Turns raw scan events into carrier and support decisions.",
  },
  {
    slug: "notifications",
    eyebrow: "Product",
    title: "Customer notifications",
    summary: "Email, SMS, and app-ready event triggers that keep customers informed at the exact point package anxiety starts.",
    bullets: ["Status-change triggers", "Delay and exception messaging", "Template-ready payloads", "Opt-in channel model"],
    proof: "Built on the same webhook feed, so notifications and API consumers agree.",
  },
  {
    slug: "self-hosting",
    eyebrow: "Product",
    title: "Self-hosting",
    summary: "Run the same API, dashboard, event pipeline, Redis, and Postgres deployment model in your own environment.",
    bullets: ["Docker compose baseline", "BYO Postgres and Redis", "Isolated processing services", "Enterprise deployment controls"],
    proof: "The differentiator: deployable infrastructure instead of a closed tracking black box.",
  },
];

export const solutionPages: MarketingPage[] = [
  {
    slug: "ecommerce",
    eyebrow: "Solution",
    title: "Ecommerce tracking",
    summary: "Reduce WISMO tickets with branded tracking pages, proactive updates, and clean package timelines for every order.",
    bullets: ["On-brand delivery pages", "Customer support deflection", "Email/SMS event triggers", "Tracking page upsell-ready slots"],
    proof: "Competes with post-purchase suites while keeping the delivery data layer flexible.",
  },
  {
    slug: "logistics-3pl",
    eyebrow: "Solution",
    title: "3PL and logistics visibility",
    summary: "Unify last-mile, postal, and cross-border legs into one normalized feed for operations teams and customer portals.",
    bullets: ["Multi-carrier shipment feed", "Cross-border handoff metadata", "Carrier health monitoring", "Bulk registration"],
    proof: "Built for teams that need to watch thousands of shipments, not one consumer package.",
  },
  {
    slug: "resellers",
    eyebrow: "Solution",
    title: "Reseller shipment monitoring",
    summary: "Track supplier shipments, customer deliveries, and marketplace orders without waiting for every carrier API contract.",
    bullets: ["Auto-detect unknown carriers", "Bulk lookup workflows", "Exception alerts", "Usage-based tracking controls"],
    proof: "Infrastructure-grade tracking makes low-margin shipment monitoring viable.",
  },
  {
    slug: "support",
    eyebrow: "Solution",
    title: "Support team console",
    summary: "Give support reps a fast, searchable shipment source of truth with clean exception language and customer-safe links.",
    bullets: ["Timeline search", "Delivery exception summaries", "Public tracking links", "Webhook/event audit trail"],
    proof: "Better package answers reduce tickets more reliably than carrier-link forwarding.",
  },
  {
    slug: "ai-agents",
    eyebrow: "Solution",
    title: "AI agent package tools",
    summary: "Expose shipment status, timelines, and subscription hooks to Claude/GPT-style agents through a dedicated MCP path.",
    bullets: ["Agent-safe tool schema", "Track package by number", "List account trackings", "Subscribe to updates"],
    proof: "A core advantage over legacy trackers that stop at dashboards and webhooks.",
  },
];

export type CarrierRecord = {
  id: string;
  name: string;
  region: string;
  status: "Live coverage" | "In rollout" | "Queued";
  tier: "Global major" | "Postal network" | "Regional" | "Cross-border";
  services: string[];
  formats: string[];
  eventCoverage: string[];
  bestFor: string[];
  reliability: string;
  updateCadence: string;
  launchStage: string;
  summary: string;
};

export const carriers: CarrierRecord[] = [
  {
    id: "usps",
    name: "USPS",
    region: "United States",
    status: "Live coverage",
    tier: "Postal network",
    services: ["Ground Advantage", "Priority Mail", "Priority Mail Express", "International inbound"],
    formats: ["94/93/92/95 IMpb numbers", "EA/CP/LH international formats", "420 destination ZIP prefixes"],
    eventCoverage: ["Accepted", "In transit", "Arrived at facility", "Out for delivery", "Delivered", "Exception"],
    bestFor: ["US ecommerce", "Marketplace sellers", "Inbound international parcels", "Support deflection"],
    reliability: "High volume, frequent scan events, strong last-mile signal.",
    updateCadence: "Status-aware monitoring for in-transit, delivery-day, and completed shipments.",
    launchStage: "Core live carrier with dashboard, API, detection, and webhook support.",
    summary: "USPS coverage anchors domestic ecommerce visibility and last-mile handoffs for inbound international parcels.",
  },
  {
    id: "ups",
    name: "UPS",
    region: "Global",
    status: "Live coverage",
    tier: "Global major",
    services: ["Ground", "2nd Day Air", "Next Day Air", "Worldwide Saver", "SurePost"],
    formats: ["1Z tracking numbers", "12-18 character package references", "Mail Innovations handoffs"],
    eventCoverage: ["Label created", "Origin scan", "Departed facility", "Import scan", "Out for delivery", "Delivered"],
    bestFor: ["B2B shipments", "US domestic parcels", "International ecommerce", "Warehouse support teams"],
    reliability: "Strong milestone density and predictable delivery-status transitions.",
    updateCadence: "Status-aware monitoring with priority refresh support for escalations.",
    launchStage: "Core live carrier with normalized service levels and timeline events.",
    summary: "UPS coverage gives operations teams reliable domestic and international package milestones.",
  },
  {
    id: "fedex",
    name: "FedEx",
    region: "Global",
    status: "Live coverage",
    tier: "Global major",
    services: ["Ground", "Home Delivery", "Express Saver", "2Day", "Priority Overnight", "International Priority"],
    formats: ["12 digit", "15 digit", "20-22 digit", "Door tag references"],
    eventCoverage: ["Shipment information sent", "Picked up", "At local facility", "Clearance", "On vehicle", "Delivered"],
    bestFor: ["Retail operations", "Express shipments", "High-value parcels", "Exception monitoring"],
    reliability: "Strong express and exception milestones with clear delivery-window semantics.",
    updateCadence: "Status-aware monitoring with delivery confirmation and exception handling.",
    launchStage: "Core live carrier with timeline, status, and API support.",
    summary: "FedEx coverage supports express, ground, and international shipments with normalized exception handling.",
  },
  {
    id: "dhl",
    name: "DHL Worldwide",
    region: "Global",
    status: "Live coverage",
    tier: "Global major",
    services: ["DHL eCommerce", "DHL Paket", "DHL Global Mail", "Cross-border parcel"],
    formats: ["10-39 character references", "JVGL/JD style references", "Postal handoff references"],
    eventCoverage: ["Processed", "Departed export facility", "Arrived destination country", "Handoff", "Delivered"],
    bestFor: ["Cross-border ecommerce", "Marketplace logistics", "Postal handoffs", "International support"],
    reliability: "Best when paired with handoff detection and destination-carrier timelines.",
    updateCadence: "Handoff-aware monitoring across export, destination arrival, and final-mile movement.",
    launchStage: "Core live carrier with cross-border event normalization.",
    summary: "DHL Worldwide coverage connects export, transit, and destination-country delivery milestones.",
  },
  {
    id: "dhl-express",
    name: "DHL Express",
    region: "Global",
    status: "Live coverage",
    tier: "Global major",
    services: ["Express Worldwide", "Express 9:00", "Express 12:00", "Document and parcel"],
    formats: ["10 digit waybills", "JD/JJD references", "Piece IDs"],
    eventCoverage: ["Picked up", "Processed at facility", "Clearance event", "With delivery courier", "Delivered"],
    bestFor: ["International express", "Time-definite shipments", "Enterprise support", "Exception alerts"],
    reliability: "Frequent international milestones and strong delivery-courier signal.",
    updateCadence: "Express monitoring profile with priority refresh support during clearance exceptions.",
    launchStage: "Core live carrier with express timeline normalization.",
    summary: "DHL Express coverage supports time-sensitive international shipments and customs-aware workflows.",
  },
  {
    id: "royal-mail",
    name: "Royal Mail",
    region: "United Kingdom",
    status: "In rollout",
    tier: "Postal network",
    services: ["Tracked 24", "Tracked 48", "Special Delivery", "International inbound"],
    formats: ["AA123456789GB", "13 character UPU formats", "domestic tracked references"],
    eventCoverage: ["Accepted", "Inward mail centre", "Ready for delivery", "Delivered", "Delivery attempted"],
    bestFor: ["UK ecommerce", "Postal inbound", "Support teams", "Delivery confirmation"],
    reliability: "Strong domestic delivery confirmation and attempted-delivery signals.",
    updateCadence: "Postal monitoring profile for first scan, transit, and delivery-day updates.",
    launchStage: "Rollout candidate with format detection and status mapping ready.",
    summary: "Royal Mail adds UK postal visibility for domestic merchants and cross-border destination legs.",
  },
  {
    id: "canada-post",
    name: "Canada Post",
    region: "Canada",
    status: "In rollout",
    tier: "Postal network",
    services: ["Expedited Parcel", "Xpresspost", "Priority", "International inbound"],
    formats: ["16 digit domestic", "AA123456789CA", "international UPU references"],
    eventCoverage: ["Shipment picked up", "Processed", "Item in transit", "Out for delivery", "Delivered"],
    bestFor: ["Canadian ecommerce", "Marketplace sellers", "Inbound international", "Bilingual support portals"],
    reliability: "Reliable national-post milestones with clear delivery and attempted-delivery states.",
    updateCadence: "Postal monitoring profile for early movement, transit, and delivery-day updates.",
    launchStage: "Rollout candidate for North American postal coverage expansion.",
    summary: "Canada Post coverage fills Canadian domestic and international inbound visibility gaps.",
  },
  {
    id: "australia-post",
    name: "Australia Post",
    region: "Australia",
    status: "In rollout",
    tier: "Postal network",
    services: ["Parcel Post", "Express Post", "StarTrack handoffs", "International inbound"],
    formats: ["AP domestic parcel IDs", "AA123456789AU", "StarTrack compatible references"],
    eventCoverage: ["Shipping information received", "In transit", "Onboard for delivery", "Delivered", "Awaiting collection"],
    bestFor: ["Australian ecommerce", "Remote delivery visibility", "Collection-point workflows", "Marketplace support"],
    reliability: "Clear delivery, collection, and attempted-delivery states across national coverage.",
    updateCadence: "Postal monitoring profile for early movement, transit, and onboard-for-delivery updates.",
    launchStage: "Rollout candidate with postal and last-mile event model.",
    summary: "Australia Post coverage supports domestic parcel visibility and collection-point customer messaging.",
  },
  {
    id: "china-post",
    name: "China Post",
    region: "China",
    status: "In rollout",
    tier: "Cross-border",
    services: ["Registered Air Mail", "ePacket", "EMS handoffs", "International parcel"],
    formats: ["AA123456789CN", "ePacket UPU references", "EMS-compatible formats"],
    eventCoverage: ["Accepted", "Exported", "Arrived destination country", "Customs", "Destination handoff", "Delivered"],
    bestFor: ["Cross-border ecommerce", "Marketplace sellers", "Destination handoffs", "Customs visibility"],
    reliability: "Best paired with destination-carrier continuation once the package enters last mile.",
    updateCadence: "Cross-border monitoring profile for origin, export, destination arrival, and handoff updates.",
    launchStage: "Rollout candidate for multi-leg cross-border timelines.",
    summary: "China Post coverage helps merge origin-country and destination-carrier events into one timeline.",
  },
  {
    id: "japan-post",
    name: "Japan Post",
    region: "Japan",
    status: "Queued",
    tier: "Postal network",
    services: ["EMS", "Registered Mail", "Yu-Pack", "International parcel"],
    formats: ["AA123456789JP", "EMS UPU references", "domestic parcel IDs"],
    eventCoverage: ["Posting", "Dispatch from outward office", "Arrival at inward office", "Final delivery"],
    bestFor: ["Japan ecommerce", "EMS visibility", "Cross-border support", "Postal delivery confirmation"],
    reliability: "Queued for event normalization and service-level mapping.",
    updateCadence: "Planned monitoring profile for postal transit and delivery-day updates.",
    launchStage: "Queued registry entry awaiting fixture validation.",
    summary: "Japan Post extends APAC postal coverage for EMS and domestic parcel visibility.",
  },
  {
    id: "dpd",
    name: "DPD",
    region: "Europe",
    status: "Queued",
    tier: "Regional",
    services: ["DPD Classic", "Predict", "Pickup parcelshop", "International road"],
    formats: ["14 digit parcel numbers", "country-specific references", "pickup point references"],
    eventCoverage: ["Order data transmitted", "At depot", "In transit", "Out for delivery", "Delivered to pickup point"],
    bestFor: ["EU ecommerce", "Pickup point delivery", "Predict windows", "Regional support"],
    reliability: "Queued for country-specific service and language normalization.",
    updateCadence: "Planned monitoring profile for in-transit and out-for-delivery updates.",
    launchStage: "Queued registry entry for EU regional rollout.",
    summary: "DPD coverage adds European parcel and pickup-point visibility for merchant portals.",
  },
  {
    id: "evri",
    name: "Evri",
    region: "United Kingdom",
    status: "Queued",
    tier: "Regional",
    services: ["Standard", "Next Day", "ParcelShop", "Courier delivery"],
    formats: ["16 character references", "domestic parcel IDs", "shop/drop-off references"],
    eventCoverage: ["We're expecting it", "At hub", "With courier", "Delivery attempt", "Delivered"],
    bestFor: ["UK ecommerce", "Low-cost last mile", "Delivery attempt alerts", "Support deflection"],
    reliability: "Queued for UK last-mile status and exception normalization.",
    updateCadence: "Planned monitoring profile for in-transit and courier-stage updates.",
    launchStage: "Queued registry entry for UK regional rollout.",
    summary: "Evri coverage targets UK last-mile visibility and customer delivery-attempt messaging.",
  },
  {
    id: "ontrac",
    name: "OnTrac",
    region: "United States",
    status: "Queued",
    tier: "Regional",
    services: ["Ground", "Ecommerce delivery", "Regional last mile", "LaserShip network"],
    formats: ["C/D prefixed references", "regional parcel IDs", "merchant references"],
    eventCoverage: ["Data received", "Package received", "Out for delivery", "Delivered", "Exception"],
    bestFor: ["US regional ecommerce", "Fast last mile", "Support teams", "Exception monitoring"],
    reliability: "Queued for regional last-mile event taxonomy.",
    updateCadence: "Planned monitoring profile for in-transit and out-for-delivery updates.",
    launchStage: "Queued registry entry for US regional coverage.",
    summary: "OnTrac coverage supports US regional last-mile visibility for ecommerce operations.",
  },
  {
    id: "yunexpress",
    name: "YunExpress",
    region: "Cross-border",
    status: "Queued",
    tier: "Cross-border",
    services: ["Standard cross-border", "Postal handoff", "Dedicated line", "Marketplace parcel"],
    formats: ["YT prefixed references", "long numeric parcel IDs", "destination handoff references"],
    eventCoverage: ["Shipment info received", "Departed origin", "Arrived destination", "Handoff", "Delivered"],
    bestFor: ["Dropshipping", "Marketplace logistics", "China-origin parcels", "Destination handoffs"],
    reliability: "Queued for handoff detection and destination-carrier stitching.",
    updateCadence: "Planned monitoring profile for origin, destination, and handoff updates.",
    launchStage: "Queued registry entry for cross-border rollout.",
    summary: "YunExpress coverage helps connect origin logistics with destination last-mile timelines.",
  },
  {
    id: "4px",
    name: "4PX",
    region: "Cross-border",
    status: "Queued",
    tier: "Cross-border",
    services: ["Express parcel", "Postal parcel", "Warehouse fulfillment", "Marketplace parcel"],
    formats: ["4PX prefixed references", "numeric parcel IDs", "UPU destination references"],
    eventCoverage: ["Picked up", "Departed facility", "Exported", "Destination arrival", "Handoff", "Delivered"],
    bestFor: ["Marketplace sellers", "Cross-border fulfillment", "Dropshipping", "Multi-leg visibility"],
    reliability: "Queued for origin and destination-leg event stitching.",
    updateCadence: "Planned monitoring profile for origin, export, and destination handoff updates.",
    launchStage: "Queued registry entry for marketplace logistics coverage.",
    summary: "4PX coverage adds cross-border fulfillment visibility for marketplace and reseller workflows.",
  },
];

export const pricingPlans = [
  ["Free", "$0", "100 trackings/mo", "5 bulk rows", "60 req/min", "Test keys, webhooks, hosted tracking"],
  ["Starter", "$19", "1,000 trackings/mo", "40 bulk rows", "300 req/min", "White-label pages, API keys, webhook inbox"],
  ["Pro", "$99", "10,000 trackings/mo", "40 bulk rows", "1,000 req/min", "Realtime hooks, analytics, priority refresh lanes"],
  ["Scale", "Usage", "Unlimited", "100 bulk rows", "5,000 req/min", "Self-host option, custom carriers, enterprise support"],
] as const;

export const comparisons = {
  "17track": {
    name: "17TRACK",
    thesis: "Match the carrier and API surface, then win on deployability, open carrier metadata, and AI-native tools.",
    rows: [["Carrier catalog", "3300+ carriers", "Registry target with open metadata"], ["API model", "HTTP + webhook", "HTTP + webhook + MCP path"], ["Hosting", "Closed SaaS", "SaaS or self-host"], ["Operations", "Opaque", "Customer-visible health and event delivery controls"]],
  },
  aftership: {
    name: "AfterShip",
    thesis: "Compete on branded tracking and notifications while offering a developer-first infrastructure layer.",
    rows: [["Tracking pages", "Strong branded pages", "White-label pages plus open API"], ["API access", "Paid plan oriented", "API-first from day one"], ["AI", "EDD/recommendations", "Agent tools and handoff intelligence"], ["Self-host", "No", "Yes"]],
  },
  trackingmore: {
    name: "TrackingMore",
    thesis: "Match tracking page, dashboard, webhook, pricing-table clarity, and carrier directory depth.",
    rows: [["Carrier directory", "1600+ couriers", "Searchable registry with coverage status"], ["Tracking pages", "Editor and multilingual", "White-label pages, embeddable path"], ["Analytics", "Shipment and engagement reports", "Carrier health and event performance"], ["Bulk", "Import/export", "Register and lookup APIs"]],
  },
  ship24: {
    name: "Ship24",
    thesis: "Match API/webhook/global coverage, then differentiate with deployable infrastructure and a broader developer platform.",
    rows: [["Coverage", "1500+ couriers", "200+ v1, registry-driven v2"], ["Webhook", "Real-time updates", "Signed webhooks with replay protection"], ["Docs", "OpenAPI import", "OpenAPI plus SDK/MCP pages"], ["Deployment", "Per-shipment SaaS", "Hosted or self-hosted infrastructure"]],
  },
} as const;
