// Patchright is a stealth-patched Playwright fork — drop-in replacement
// for `playwright` that ships with proper navigator.webdriver removal,
// canvas/WebGL fingerprint normalization, and Chrome runtime spoofing.
// Significantly more reliable against Akamai sensor.js / Cloudflare /
// PerimeterX than playwright-extra + stealth-plugin (which leaves the
// CDP traces patchright actually scrubs).
import { chromium } from "patchright";
import type { APIRequestContext, Browser, BrowserContext, Page } from "patchright";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ScrapeResult } from "./types.ts";

const BLOCKED_TYPES = new Set(["image", "font", "media", "stylesheet"]);
const BLOCKED_DOMAINS = [
  "googletagmanager.com",
  "google-analytics.com",
  "googleadservices.com",
  "doubleclick.net",
  "facebook.com",
  "facebook.net",
  "fast.fonts.net",
  "adobedtm.com",
  "demdex.net",
  "digital.nuance.com",
  "media-us2.digital.nuance.com",
  "usercentrics.eu",
  "optimizely.com",
  "smetrics.fedex.com",
  "evergage.com",
];

interface CarrierBase {
  /** Stable identifier, e.g. "usps". */
  readonly name: string;
  /**
   * Optional. Inspect a failed result and decide whether the session has
   * expired (Akamai cookie aged out, OAuth token rejected, etc.).
   */
  isExpired?(result: ScrapeResult): boolean;
}

/** Bundle passed to ScraperCarrier.runQuery. */
export interface QueryCtx {
  /** The warm Page — use for DOM parsing or carrier-specific signals
   *  (cookies, page.url() checks). DO NOT use for the data fetch. */
  page: Page;
  /** Raw HTTP request bound to the warm context.
   *  Prefer page.evaluate(fetch) for anti-bot-sensitive carrier fetches so
   *  the request uses Chrome's TLS/fingerprint path. */
  request: APIRequestContext;
}

export interface ScraperCarrier extends CarrierBase {
  readonly mode: "scraper";
  /** Initial URL to load to mint anti-bot cookies + any auth tokens. */
  warmUrl(num: string): string;
  /**
   * Optional. Called once per warm, AFTER the new Page is created but BEFORE
   * the warm navigation runs. Use this to attach response listeners (e.g. to
   * capture an OAuth bearer token).
   */
  setupPage?(page: Page): void | Promise<void>;
  /**
   * Optional. Called AFTER the warm navigation lands. Use to wait for a
   * carrier-specific "session is now valid" signal.
   */
  awaitReady?(page: Page, num: string): Promise<void>;
  /** Execute one tracking lookup through the warmed browser context. */
  runQuery(ctx: QueryCtx, num: string): Promise<ScrapeResult>;
  /** Keep warm-phase routing after warm when a carrier's app must render repeated lookups. */
  keepWarmRouting?: boolean;
}

export type Carrier = ScraperCarrier;

export interface SessionOptions {
  /** Default true. Set false to see the browser window (helpful when debugging). */
  headless?: boolean;
  /**
   * Which browser channel to use. Defaults to Playwright's bundled Chromium.
   * Set "chrome" or "msedge" to use the system browser — required for some
   * carriers (notably UPS, which uses reCAPTCHA that detects bundled Chromium
   * but not system Chrome).
   */
  channel?: "chrome" | "msedge";
  /** Fired each time we (re)warm the session. Useful for telemetry / logging. */
  onWarm?: () => void;
  /** Forwarded to the carrier in case it wants verbose logging. */
  debug?: boolean;
  /** Set null to keep the browser's native user-agent. */
  userAgent?: string | null;
  /** Disable request blocking for carriers whose own JS/pixels are required. */
  disableBlocking?: boolean;
  /** Optional persistent browser profile. Useful for carriers that require
   *  first-party browser state generated by their own JS before API calls work. */
  persistentProfileDir?: string;
  /** Max time for the initial warm navigation. Defaults to 60s. */
  warmTimeoutMs?: number;
  /** Navigation readiness target for the warm page. Defaults to full load. */
  warmWaitUntil?: "load" | "domcontentloaded" | "networkidle" | "commit";
  /** Proxy used by the browser context. Keep warm and query traffic on it. */
  proxy?: {
    server: string;
    username?: string;
    password?: string;
  };
  /** Use a Chrome extension to set/authenticate the proxy instead of Playwright's proxy option. */
  proxyMode?: "native" | "extension";
  /** Attach to an already-running Chrome instance, e.g. http://127.0.0.1:9222. */
  cdpEndpoint?: string;
  /** Extra Chromium launch args for carrier-specific transport workarounds. */
  launchArgs?: string[];
  /** Browser-surface spoofing profile for anti-bot-sensitive carriers. */
  fingerprintProfile?: "mac-chrome";
}

const DEFAULT_EXPIRED_MARKERS =
  /access denied|edgesuite|akamai bot|forbidden|403|_abck|session expired/i;

export class TrackingSession {
  private browser: Browser | null = null;
  private context: BrowserContext | null = null;
  private page: Page | null = null;
  private browserProcess: { kill(signal?: NodeJS.Signals | number): boolean } | null = null;
  private attachedBrowser = false;
  private _warm = false;

  constructor(
    private readonly carrier: Carrier,
    private readonly opts: SessionOptions = {},
  ) {}

  get warm(): boolean {
    return this._warm;
  }

  async track(num: string): Promise<ScrapeResult> {
    try {
      await this.ensureWarm(num);
      let result = await this.carrier.runQuery(this.ctx(), num);

      if (!result.ok && this.detectExpired(result)) {
        if (this.opts.debug)
          console.error(`[session:${this.carrier.name}] expiry detected, re-warming`);
        this._warm = false;
        await this.ensureWarm(num);
        result = await this.carrier.runQuery(this.ctx(), num);
      }
      return result;
    } catch (err) {
      return {
        ok: false,
        error: `${this.carrier.name}: ${formatCarrierError(err)}`,
      };
    }
  }

  /** Pack page + request into the QueryCtx the carrier expects. */
  private ctx(): QueryCtx {
    return { page: this.page!, request: this.context!.request };
  }

  async close(): Promise<void> {
    // Tear down in reverse order. System Chrome can occasionally hang on
    // close, so every close operation is bounded.
    if (!this.attachedBrowser && this.opts.channel && this.browserProcess) {
      try { this.browserProcess.kill("SIGTERM"); } catch { /* */ }
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
    if (this.page && !this.attachedBrowser) await closeWithTimeout(() => this.page!.close(), 3000);
    if (this.context && !this.attachedBrowser) await closeWithTimeout(() => this.context!.close(), 5000);
    if (this.browser && !this.attachedBrowser) {
      const closed = await closeWithTimeout(() => this.browser!.close(), 5000);
      if (!closed) {
        try { this.browserProcess?.kill("SIGTERM"); } catch { /* */ }
      }
    }
    this.page = null;
    this.context = null;
    this.browser = null;
    this.browserProcess = null;
    this.attachedBrowser = false;
    this._warm = false;
  }

  private async ensureWarm(num: string): Promise<void> {
    if (this._warm && this.page) return;

    // Close stale page/context if a prior warm partially failed.
    if (this.page) {
      try { await this.page.close(); } catch { /* */ }
      this.page = null;
    }
    if (this.context) {
      try { await this.context.close(); } catch { /* */ }
      this.context = null;
    }

    const extensionProxy =
      this.opts.proxy && this.opts.proxyMode === "extension"
        ? createProxyExtension(this.opts.proxy, this.carrier.name)
        : null;

    const contextOptions = {
      ...(this.opts.userAgent === null
        ? {}
        : {
            userAgent:
              this.opts.userAgent ??
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
                "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
          }),
      viewport: { width: 1280, height: 800 },
      locale: "en-US",
      ...(this.opts.proxy && !extensionProxy ? { proxy: this.opts.proxy } : {}),
    };

    const extensionArgs = extensionProxy
      ? [
          `--disable-extensions-except=${extensionProxy}`,
          `--load-extension=${extensionProxy}`,
        ]
      : [];
    const launchArgs = [
      "--disable-blink-features=AutomationControlled",
      ...extensionArgs,
      ...(this.opts.launchArgs ?? []),
    ];

    if (this.opts.cdpEndpoint) {
      this.browser = await chromium.connectOverCDP(this.opts.cdpEndpoint, { noDefaults: true });
      this.attachedBrowser = true;
      const deadline = Date.now() + 10_000;
      while (!this.browser.contexts().length && Date.now() < deadline) {
        await new Promise((resolve) => setTimeout(resolve, 250));
      }
      this.context = this.browser.contexts()[0] ?? null;
      if (!this.context) {
        throw new Error(`CDP browser at ${this.opts.cdpEndpoint} has no available context`);
      }
    } else if (this.opts.persistentProfileDir) {
      const persistentOptions = {
        ...contextOptions,
        headless: this.opts.headless ?? true,
        args: launchArgs,
      };
      try {
        this.context = await chromium.launchPersistentContext(
          this.opts.persistentProfileDir,
          {
            ...persistentOptions,
            ...(this.opts.channel ? { channel: this.opts.channel } : {}),
          },
        );
      } catch (err) {
        if (!this.opts.channel) throw err;
        if (this.opts.debug) {
          console.error(
            `[session:${this.carrier.name}] launchPersistentContext with channel=${this.opts.channel} failed; retrying bundled Chromium: ${formatCarrierError(err)}`,
          );
        }
        this.context = await chromium.launchPersistentContext(
          this.opts.persistentProfileDir,
          persistentOptions,
        );
      }
      this.browser = this.context.browser();
      this.browserProcess =
        (this.browser as unknown as {
          process?: () => { kill(signal?: NodeJS.Signals | number): boolean } | null;
        })?.process?.() ?? null;
    } else {
      if (!this.browser) {
        try {
          this.browser = await chromium.launch({
            headless: this.opts.headless ?? true,
            args: launchArgs,
            ...(this.opts.channel ? { channel: this.opts.channel } : {}),
          });
        } catch (err) {
          if (!this.opts.channel) throw err;
          if (this.opts.debug) {
            console.error(
              `[session:${this.carrier.name}] launch with channel=${this.opts.channel} failed; retrying bundled Chromium: ${formatCarrierError(err)}`,
            );
          }
          this.browser = await chromium.launch({
            headless: this.opts.headless ?? true,
            args: launchArgs,
          });
        }
        this.browserProcess =
          (this.browser as unknown as {
            process?: () => { kill(signal?: NodeJS.Signals | number): boolean } | null;
          }).process?.() ?? null;
      }
      this.context = await this.browser.newContext(contextOptions);
    }

    if (this.opts.fingerprintProfile === "mac-chrome") {
      await applyMacChromeFingerprint(this.context);
    }

    // Two-phase blocker:
    //   Phase 1 (warm): block heavy resource types + ad domains, but let
    //   the SPA's own JS/CSS through so Akamai's sensor.js can run + mint
    //   cookies. Without these the warm fails at awaitReady.
    //   Phase 2 (post-warm): tighten to ONLY allow HTML + JSON + Akamai
    //   sensor pings. Every subsequent page.evaluate(fetch) returns just
    //   the tracking-page HTML; React chrome bundles + analytics + new
    //   JS chunks all get aborted. Per-query bandwidth ≈ HTML body only.
    let postWarm = false;
    if (!process.env.NO_BLOCKING && !this.opts.disableBlocking) {
      await this.context.route("**/*", (route, req) => {
        const url = req.url();
        if (postWarm) {
          if (req.method() === "OPTIONS") return route.continue();
          // Tightened: keep only navigations/document fetches + JSON,
          // and Akamai sensor pings (they keep the session valid).
          const rt = req.resourceType();
          if (rt === "document" || rt === "xhr" || rt === "fetch") return route.continue();
          if (url.includes(".json")) return route.continue();
          if (/akamai|edgesuite|_abck/i.test(url)) return route.continue();
          return route.abort();
        }
        if (BLOCKED_TYPES.has(req.resourceType())) return route.abort();
        if (BLOCKED_DOMAINS.some((d) => url.includes(d))) return route.abort();
        return route.continue();
      });
    }
    // Expose so the warm flow below can flip the switch after awaitReady.
    (this as unknown as { _flipPostWarm: () => void })._flipPostWarm = () => {
      postWarm = true;
    };

    this.page = await this.context.newPage();

    const scraperForSetup = this.carrier as ScraperCarrier;
    if (scraperForSetup.setupPage) {
      await scraperForSetup.setupPage(this.page);
    }

    if (extensionProxy) {
      await this.page.waitForTimeout(proxyExtensionSettleMs(this.carrier.name));
    }

    await this.page.goto(this.carrier.warmUrl(num), {
      waitUntil: this.opts.warmWaitUntil ?? "load",
      timeout: this.opts.warmTimeoutMs ?? 60000,
    });

    // Anti-bot scripts (Akamai sensor, etc.) often finish minting cookies AFTER
    // page load. The carrier can override with a precise readiness selector;
    // otherwise we fall back to a short fixed wait.
    if (this.carrier.awaitReady) {
      try {
        await this.carrier.awaitReady(this.page, num);
      } catch (err) {
        if (this.opts.debug) {
          console.error(
            `[session:${this.carrier.name}] readiness check failed: ${formatCarrierError(err)}`,
          );
        }
      }
    } else {
      await this.page.waitForTimeout(3000);
    }

    this._warm = true;
    // Flip the route blocker into "block everything but HTML/JSON" mode now
    // that anti-bot cookies are valid. Per-query bandwidth collapses to the
    // size of the response body.
    if (!this.carrier.keepWarmRouting) {
      (this as unknown as { _flipPostWarm?: () => void })._flipPostWarm?.();
    }
    this.opts.onWarm?.();
  }

  private detectExpired(result: ScrapeResult): boolean {
    if (this.carrier.isExpired) return this.carrier.isExpired(result);
    return DEFAULT_EXPIRED_MARKERS.test(result.error || "");
  }
}

async function applyMacChromeFingerprint(context: BrowserContext): Promise<void> {
  await context.setExtraHTTPHeaders({
    "sec-ch-ua": "\"Google Chrome\";v=\"149\", \"Chromium\";v=\"149\", \"Not)A;Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
  });
  await context.addInitScript(() => {
    const defineGetter = (target: object, key: string, value: unknown) => {
      try {
        Object.defineProperty(target, key, { get: () => value, configurable: true });
      } catch {
        // Ignore locked browser fields.
      }
    };

    defineGetter(Navigator.prototype, "platform", "MacIntel");
    defineGetter(Navigator.prototype, "hardwareConcurrency", 8);
    defineGetter(Navigator.prototype, "deviceMemory", 8);
    defineGetter(Navigator.prototype, "maxTouchPoints", 0);
    defineGetter(Navigator.prototype, "vendor", "Google Inc.");
    defineGetter(Navigator.prototype, "languages", ["en-US", "en"]);
    defineGetter(Navigator.prototype, "webdriver", undefined);

    const originalResolvedOptions = Intl.DateTimeFormat.prototype.resolvedOptions;
    Intl.DateTimeFormat.prototype.resolvedOptions = function resolvedOptions() {
      return {
        ...originalResolvedOptions.call(this),
        timeZone: "America/New_York",
      };
    };

    const getParameter = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function getParameterSpoof(parameter) {
      if (parameter === 37445) return "Intel Inc.";
      if (parameter === 37446) return "Intel Iris OpenGL Engine";
      return getParameter.call(this, parameter);
    };
  });
}

export function createProxyExtension(
  proxy: NonNullable<SessionOptions["proxy"]>,
  carrierName: string,
): string {
  const parsed = new URL(normalizeProxyServer(proxy.server));
  const scheme = parsed.protocol.replace(":", "") || "http";
  const host = parsed.hostname;
  const port = Number(parsed.port || (scheme === "https" ? 443 : 80));
  const dir = join(process.cwd(), ".browser-profiles", "proxy-extensions", carrierName);
  mkdirSync(dir, { recursive: true });
  const useManifestV2 = process.env.PROXY_EXTENSION_MANIFEST_VERSION === "2";
  writeFileSync(
    join(dir, "manifest.json"),
    JSON.stringify(useManifestV2
      ? {
          manifest_version: 2,
          name: "Trackified Proxy",
          version: "1.0.0",
          permissions: ["proxy", "webRequest", "webRequestBlocking", "<all_urls>"],
          background: { scripts: ["background.js"], persistent: true },
        }
      : {
          manifest_version: 3,
          name: "Trackified Proxy",
          version: "1.0.0",
          permissions: ["proxy", "webRequest", "webRequestAuthProvider", "storage"],
          host_permissions: ["<all_urls>"],
          background: { service_worker: "background.js" },
        },
    null,
    2),
  );
  writeFileSync(
    join(dir, "background.js"),
    `
const config = {
  mode: "fixed_servers",
  rules: {
    singleProxy: {
      scheme: ${JSON.stringify(scheme)},
      host: ${JSON.stringify(host)},
      port: ${JSON.stringify(port)}
    },
    bypassList: []
  }
};

chrome.proxy.settings.set({ value: config, scope: "regular" });

chrome.webRequest.onAuthRequired.addListener(
  () => ({
    authCredentials: {
      username: ${JSON.stringify(proxy.username ?? "")},
      password: ${JSON.stringify(proxy.password ?? "")}
    }
  }),
  { urls: ["<all_urls>"] },
  ["blocking"]
);
`.trimStart(),
  );
  return dir;
}

function normalizeProxyServer(server: string): string {
  return /^[a-z][a-z\d+.-]*:\/\//i.test(server) ? server : `http://${server}`;
}

function proxyExtensionSettleMs(carrierName: string): number {
  const key = `PROXY_EXTENSION_SETTLE_MS_${carrierName.toUpperCase().replaceAll("-", "_")}`;
  return Number(process.env[key] ?? process.env.PROXY_EXTENSION_SETTLE_MS ?? 3000);
}

function formatCarrierError(err: unknown): string {
  const raw = err instanceof Error ? err.message : typeof err === "string" ? err : null;
  if (raw) return sanitizeCarrierError(raw);
  try {
    return sanitizeCarrierError(JSON.stringify(err));
  } catch {
    return sanitizeCarrierError(String(err));
  }
}

function sanitizeCarrierError(message: string): string {
  const withoutAnsi = message.replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, "");
  const summary = withoutAnsi.split(/\nCall log:/)[0] ?? withoutAnsi;
  return summary.length > 700 ? `${summary.slice(0, 700)}...` : summary;
}

async function closeWithTimeout(
  fn: () => Promise<unknown>,
  timeoutMs: number,
): Promise<boolean> {
  try {
    await Promise.race([
      fn(),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error("close timeout")), timeoutMs),
      ),
    ]);
    return true;
  } catch {
    return false;
  }
}

/** One-shot convenience: warm, run one query, close. */
export async function trackOnce(
  carrier: Carrier,
  num: string,
  opts?: SessionOptions,
): Promise<ScrapeResult> {
  const s = new TrackingSession(carrier, opts);
  try {
    return await s.track(num);
  } finally {
    await s.close();
  }
}
